/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Calendario;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import static jdk.nashorn.internal.runtime.Debug.id;


/**
 *
 * @author Jorge
 */
public class Login extends javax.swing.JPanel {

    private Main main;

    public Login(Main main) {
        this.main = main;
        initComponents();
    }
    public static User currentUser;


  public void ingresar() {
    String usuario = jTxtUsuarioL.getText().trim();
    String contrasenia = new String(jPswContraseniaL.getPassword()).trim();

    DatabaseCompleto db = new DatabaseCompleto();
    User user = db.validateLogin(usuario, contrasenia);

    if (user != null) {
        JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.");

        Login.currentUser = user;
        // Mostrar la agenda
        Agenda agenda = new Agenda(user);
        agenda.setVisible(true);

        // Cerrar ventana actual (Login)
        SwingUtilities.getWindowAncestor(this).dispose();
        

    } else {
        JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtUsuarioL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPswContraseniaL = new javax.swing.JPasswordField();
        jBtnIngresar = new javax.swing.JButton();
        jBtnNoTieneCuenta = new javax.swing.JButton();

        setBackground(new java.awt.Color(30, 30, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesión");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");

        jTxtUsuarioL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTxtUsuarioL.setPreferredSize(new java.awt.Dimension(64, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");

        jPswContraseniaL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jPswContraseniaL.setPreferredSize(new java.awt.Dimension(64, 50));

        jBtnIngresar.setBackground(new java.awt.Color(204, 0, 0));
        jBtnIngresar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jBtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIngresar.setText("Ingresar");
        jBtnIngresar.setPreferredSize(new java.awt.Dimension(0, 50));
        jBtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresarActionPerformed(evt);
            }
        });

        jBtnNoTieneCuenta.setBackground(new java.awt.Color(41, 41, 41));
        jBtnNoTieneCuenta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jBtnNoTieneCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNoTieneCuenta.setText("¿No tienes una cuenta? Registrate");
        jBtnNoTieneCuenta.setPreferredSize(new java.awt.Dimension(0, 50));
        jBtnNoTieneCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNoTieneCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtUsuarioL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPswContraseniaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnNoTieneCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtUsuarioL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPswContraseniaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnNoTieneCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresarActionPerformed
         // usa tus datos reales
// TODO add your handling code here:
        ingresar();
    }//GEN-LAST:event_jBtnIngresarActionPerformed

    private void jBtnNoTieneCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNoTieneCuentaActionPerformed
        // TODO add your handling code here:
        main.setRegister();
    }//GEN-LAST:event_jBtnNoTieneCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIngresar;
    private javax.swing.JButton jBtnNoTieneCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPswContraseniaL;
    private javax.swing.JTextField jTxtUsuarioL;
    // End of variables declaration//GEN-END:variables
}
